/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2017 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package firebase.crashlytics;


import com.google.firebase.crashlytics.FirebaseCrashlytics;
import com.google.firebase.crashlytics.internal.common.CrashlyticsCore;

import org.appcelerator.kroll.KrollDict;
import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;
import org.appcelerator.kroll.common.Log;
import org.appcelerator.kroll.common.TiConfig;
import org.appcelerator.titanium.TiApplication;
import org.appcelerator.titanium.util.TiConvert;

import java.util.HashMap;



@Kroll.module(name="FirebaseCrashlytics", id="firebase.crashlytics")
public class FirebaseCrashlyticsModule extends KrollModule
{

	// Standard Debugging variables
	private static final String LCAT = "FirebaseCrashlyticsModule";
	private static final boolean DBG = TiConfig.LOGD;

	// You can define constants with @Kroll.constant, for example:
	// @Kroll.constant public static final String EXTERNAL_NAME = value;

	public FirebaseCrashlyticsModule()
	{
		super();
	}

	@Kroll.onAppCreate
	public static void onAppCreate(TiApplication app)
	{
		Log.d(LCAT, "inside onAppCreate");
	}

    // Methods
    @Kroll.method
    public void initialize(HashMap hm)
    {
        KrollDict args = new KrollDict(hm);
        boolean isDebuggable = args.optBoolean("debuggable", false);
    }


	@Kroll.method
	public void log(String value) {
        FirebaseCrashlytics.getInstance().log(value);
	}

    @Kroll.method
	public void crash() {
        throw new RuntimeException("Test Crash"); // Force a crash
	}

    @Kroll.method
    public void throwException()
    {
        try {
            throw new RuntimeException("This is a crash");
        } catch (RuntimeException e) {
            FirebaseCrashlytics.getInstance().recordException(e);
        }
    }

    @Kroll.method
    public void setUserIdentifier(String userIdentifier) {
        Log.d(LCAT, "Crashlytics setUserIdentifier"+userIdentifier);
        FirebaseCrashlytics.getInstance().setUserId(userIdentifier);
    }


    @Kroll.method
    public void setString(Object[] args) {

        // This method is an example of exposing a native method that accepts 2
        // arguments (2 string values).
        // The method signature declares an array of objects, so it is necessary
        // to validate the number of arguments passed to the method.

        final int kArgValue = 0;
        final int kArgKey = 1;
        final int kArgCount = 2;

        // Validate correct number of arguments
        if (args.length < kArgCount) {
            throw new IllegalArgumentException("At least 2 arguments required for setObjectValue: value, key");
        }

        // Use the TiConvert methods to get the values from the arguments
        String value = TiConvert.toString(args[kArgValue]);
        String key = TiConvert.toString(args[kArgKey]);
        //int age = (args[kArgAge] != null) ? TiConvert.toInt(args[kArgAge]) : 0;

        FirebaseCrashlytics.getInstance().setCustomKey(key, value);
    }

    @Kroll.method
    public void setInt(Object[] args) {

        // This method is an example of exposing a native method that accepts 2
        // arguments (2 string values).
        // The method signature declares an array of objects, so it is necessary
        // to validate the number of arguments passed to the method.

        final int kArgValue = 0;
        final int kArgKey = 1;
        final int kArgCount = 2;

        // Validate correct number of arguments
        if (args.length < kArgCount) {
            throw new IllegalArgumentException("At least 2 arguments required for setInt: value, key");
        }

        // Use the TiConvert methods to get the values from the arguments
        int value = (args[kArgValue] != null) ? TiConvert.toInt(args[kArgValue]) : 0;
        String key = TiConvert.toString(args[kArgKey]);

        FirebaseCrashlytics.getInstance().setCustomKey(key, value);
    }

    @Kroll.method
    public void setBool(Object[] args) {

        // This method is an example of exposing a native method that accepts 2
        // arguments (2 string values).
        // The method signature declares an array of objects, so it is necessary
        // to validate the number of arguments passed to the method.

        final int kArgValue = 0;
        final int kArgKey = 1;
        final int kArgCount = 2;

        // Validate correct number of arguments
        if (args.length < kArgCount) {
            throw new IllegalArgumentException("At least 2 arguments required for setBool: value, key");
        }

        // Use the TiConvert methods to get the values from the arguments
        boolean value = TiConvert.toBoolean(args[kArgValue]);
        String key = TiConvert.toString(args[kArgKey]);

        FirebaseCrashlytics.getInstance().setCustomKey(key, value);
    }

}
